name:                inkball
version:             0.1.0
github:              "ghallak/inkball"
author:              "Gaith Hallak"
maintainer:          "gaithhallak@gmail.com"
copyright:           "2018 Gaith Hallak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/inkball#readme>

dependencies:
- base >= 4.7 && < 5
- sdl2
- text

library:
  source-dirs: src

executables:
  inkball:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inkball

tests:
  inkball-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - inkball
